INSERT INTO public.healing_plan_days (day_number, title, content, prompt, challenge, mindset_reframe, action_item) VALUES
(6, 'Building Boundaries', 'Today we focus on establishing healthy boundaries in all areas of your life. Boundaries are not walls to keep people out, but guidelines that help you maintain your self-respect and emotional well-being.', 'What boundaries do I need to set to protect my peace and energy?', 'Communicate one boundary clearly to someone in your life today', 'Boundaries are not selfish - they are essential for healthy relationships', 'Write down 3 specific boundaries you need in your life right now'),

(7, 'Releasing Attachment', 'Attachment to outcomes and expectations can keep us stuck in pain. Today we practice letting go of how things "should" be and accepting what is, while working toward what could be.', 'What am I holding onto that no longer serves me?', 'Practice letting go of one expectation you have been clinging to', 'Letting go is not giving up - it is making space for something better', 'Do a physical releasing ritual - write down what you want to let go of and safely dispose of the paper'),

(8, 'Inner Child Healing', 'We all carry wounded parts from our past. Today we focus on healing your inner child - the part of you that may feel abandoned, rejected, or unloved.', 'What does my inner child need to hear right now?', 'Speak to yourself with the kindness you would show a hurt child', 'I am worthy of love and care, exactly as I am', 'Write a loving letter to your younger self, offering comfort and encouragement'),

(9, 'Creating Safety', 'After heartbreak, we often feel unsafe in the world. Today we focus on creating emotional and physical safety for yourself, building a foundation for healing.', 'What makes me feel truly safe and secure?', 'Create one element of safety in your environment today', 'I am capable of creating safety and security for myself', 'Establish a daily routine that makes you feel grounded and secure'),

(11, 'Gratitude Practice', 'Gratitude shifts our focus from what we have lost to what we still have. Even in pain, there are always things to be grateful for, no matter how small.', 'What am I genuinely grateful for in this moment?', 'Share your gratitude with someone who has supported you', 'Gratitude transforms my perspective and opens my heart to possibilities', 'Write down 5 things you are grateful for, including one thing about yourself'),

(12, 'Energy Management', 'Healing requires energy, and we must learn to protect and nurture our energy like a precious resource. Today we focus on what drains you and what restores you.', 'What activities, people, or situations drain my energy versus restore it?', 'Eliminate or reduce one energy-draining activity from your day', 'I honor my energy and choose how to spend it wisely', 'Create an energy audit - list what drains you and what energizes you'),

(13, 'Reclaiming Joy', 'Joy might feel foreign after heartbreak, but small moments of joy are still available to you. Today we practice noticing and creating micro-moments of happiness.', 'What brought me joy before my heartbreak, and what might bring me joy now?', 'Engage in one activity purely for the joy of it', 'Joy is my birthright and it is safe for me to experience happiness', 'Do something that made you smile as a child'),

(14, 'Social Connection', 'Healing happens in relationship with others. Today we focus on nurturing healthy connections and seeking support from those who truly care about you.', 'Who in my life makes me feel seen, heard, and valued?', 'Reach out to someone who supports your healing journey', 'I deserve relationships that are loving, supportive, and reciprocal', 'Schedule quality time with someone who brings out the best in you'),

(16, 'Creative Expression', 'Creativity is a powerful healing tool that allows us to express what words cannot capture. Today we explore creative ways to process and release emotions.', 'How can I express my emotions creatively?', 'Create something with your hands - art, music, writing, cooking, or crafting', 'My creativity is a gift that helps me heal and express my truth', 'Spend 30 minutes in creative expression without judgment or expectation'),

(17, 'Physical Healing', 'Our bodies hold emotional pain and trauma. Today we focus on caring for your physical self as an act of love and a pathway to emotional healing.', 'How is my emotional pain showing up in my body?', 'Do one thing to honor and care for your physical body', 'My body is wise and deserves love, care, and respect', 'Take a mindful walk, stretch, or engage in gentle movement'),

(18, 'Spiritual Connection', 'Whether through nature, meditation, prayer, or personal practices, connecting with something greater than ourselves can provide comfort and perspective during difficult times.', 'What helps me feel connected to something greater than myself?', 'Spend time in a practice that nurtures your spiritual well-being', 'I am part of something beautiful and meaningful', 'Engage in a spiritual practice that resonates with you - meditation, prayer, nature, or reflection'),

(19, 'Processing Anger', 'Anger is a natural and necessary part of the healing process. Today we learn to feel, express, and release anger in healthy ways without suppressing or projecting it.', 'What am I angry about, and what is this anger trying to tell me?', 'Express your anger in a safe and healthy way', 'My anger is valid and contains important information about my boundaries and values', 'Write an uncensored letter expressing your anger (you do not have to send it)'),

(20, 'Rewriting Your Story', 'You are not just what happened to you. Today we practice seeing yourself as the author of your life story, with the power to write new chapters.', 'If I am the author of my life, what story do I want to tell going forward?', 'Take one action that aligns with the person you are becoming', 'I am not defined by my past - I am empowered to create my future', 'Write a brief story about the person you are becoming and the life you are creating'),

(22, 'Trust Building', 'After betrayal or heartbreak, trust feels scary. Today we focus on rebuilding trust - starting with trusting yourself and your own judgment.', 'How can I begin to trust myself and my decisions again?', 'Make one decision today based on trusting your own judgment', 'I can trust myself to make decisions that are in my best interest', 'Practice listening to your intuition about a small decision and follow through'),

(23, 'Self-Love Practices', 'Self-love is not narcissism - it is the foundation of all healthy relationships. Today we practice concrete ways to love and care for yourself.', 'How can I show love to myself in the same way I would show love to someone I care about?', 'Do one act of genuine self-care or kindness for yourself', 'I am worthy of love, especially my own', 'Treat yourself with the same kindness you would show your best friend'),

(24, 'Purpose and Meaning', 'Pain can be transformed into purpose. Today we explore how your experiences might serve a greater meaning in your life or in helping others.', 'How might my experiences help me grow or serve others?', 'Connect with a cause or activity that gives your life meaning', 'My experiences, including my pain, have value and can contribute to something meaningful', 'Volunteer, mentor, or support someone else in a small way'),

(25, 'Celebrating Progress', 'Healing is not linear, and progress is not always obvious. Today we pause to acknowledge how far you have come on this journey.', 'What positive changes have I noticed in myself since beginning this healing journey?', 'Celebrate one area of growth or progress you have made', 'I acknowledge my strength, courage, and commitment to healing', 'Do something special to celebrate your progress - treat yourself or share your growth with someone you trust'),

(26, 'Future Relationships', 'Healing prepares us for healthier future relationships. Today we reflect on what you have learned and what you want in future connections.', 'What do I now know about what I want and need in relationships?', 'Write down your relationship values and non-negotiables', 'I am becoming clearer about what I deserve in relationships', 'Create a list of qualities you want in future relationships and qualities you want to develop in yourself'),

(27, 'Integration', 'Today we integrate all the lessons, insights, and growth from your healing journey. You are not the same person who began this process.', 'How have I grown and changed through this healing process?', 'Share one important insight from your healing journey with someone you trust', 'I have grown stronger, wiser, and more aligned with who I truly am', 'Write a letter to yourself acknowledging your growth and the wisdom you have gained'),

(28, 'Wisdom and Compassion', 'Your pain has been transformed into wisdom and compassion. Today we reflect on the gifts that have emerged from your healing journey.', 'What wisdom have I gained that I would want to share with someone else going through heartbreak?', 'Offer compassion or support to someone else who is struggling', 'My experiences have made me wiser and more compassionate', 'Practice extending compassion to yourself and to someone else today'),

(29, 'New Beginnings', 'Tomorrow is the final day of this structured journey, but it is also the beginning of a new chapter in your life. Today we prepare for this transition.', 'What new beginnings am I ready to embrace in my life?', 'Take one concrete step toward a new goal or aspiration', 'I am ready to embrace new possibilities and opportunities', 'Plan or begin something new that excites you - a hobby, goal, or adventure');