-- Clear existing journal prompts and insert all 30 new ones
DELETE FROM journal_prompts;

INSERT INTO journal_prompts (prompt, category, emotional_theme) VALUES
('Write about the relationship patterns you''ve noticed in your life. What themes keep appearing, and what might they be trying to teach you?', 'Self-Reflection', 'Pattern Recognition'),
('Describe a moment when you felt truly loved and accepted. What did that experience teach you about your own worth?', 'Self-Love', 'Self-Worth'),
('What are three things you''re grateful for about yourself today? Focus on your inner qualities rather than achievements.', 'Gratitude', 'Self-Appreciation'),
('Write a letter to your past self who was going through heartbreak. What wisdom would you share?', 'Healing', 'Growth'),
('What does your ideal relationship look like? Describe how you want to feel and be treated.', 'Future Visioning', 'Hope'),
('Reflect on a recent conflict or difficult conversation. What were the underlying emotions and needs that weren''t expressed?', 'Communication', 'Understanding'),
('What fears do you have about relationships? Where do you think these fears originated, and how do they serve or limit you?', 'Fears', 'Courage'),
('Write about a boundary you need to set or maintain. What makes this boundary important for your wellbeing?', 'Boundaries', 'Self-Protection'),
('Describe how you''ve grown as a person through your relationship experiences. What strengths have you developed?', 'Growth', 'Empowerment'),
('What would you tell someone else who is going through a similar situation to yours? Write this advice with compassion.', 'Wisdom', 'Compassion'),
('Reflect on your attachment style. How does it show up in your relationships, and what would healing look like?', 'Attachment', 'Awareness'),
('Write about a moment when you chose yourself over staying in an unhealthy situation. How did that feel?', 'Self-Advocacy', 'Pride'),
('What are your core values in relationships? How can you honor these values in future connections?', 'Values', 'Alignment'),
('Describe what peace feels like to you. How can you create more of this feeling in your daily life?', 'Peace', 'Serenity'),
('Write about forgiveness - either forgiving someone else or forgiving yourself. What would that process look like?', 'Forgiveness', 'Release'),
('What does self-compassion mean to you? How can you practice being kinder to yourself during difficult times?', 'Self-Love', 'Kindness'),
('Write about a time when you felt truly confident and secure. What internal and external factors contributed to that feeling?', 'Confidence', 'Security'),
('What toxic patterns are you ready to release? Write about why you''re committed to breaking these cycles.', 'Transformation', 'Liberation'),
('Describe your emotional support system. Who are the people that truly see and understand you?', 'Support', 'Connection'),
('What would you want to tell your future self about the journey you''re on now? What hopes do you have?', 'Future Visioning', 'Optimism'),
('Write about a moment when you stood up for yourself. How did it feel, and what did you learn about your own strength?', 'Self-Advocacy', 'Empowerment'),
('What does vulnerability look like in healthy relationships? How comfortable are you with being truly seen?', 'Intimacy', 'Authenticity'),
('Reflect on your relationship with solitude. How do you feel when you''re alone with your thoughts?', 'Self-Reflection', 'Independence'),
('What childhood experiences shaped your understanding of love? How do these influences show up in your adult relationships?', 'Origins', 'Understanding'),
('Write about a time when you felt deeply grateful for a difficult experience. What did it teach you?', 'Gratitude', 'Wisdom'),
('What does emotional safety feel like to you? How can you create this for yourself and others?', 'Safety', 'Security'),
('Describe your relationship with trust. What helps you feel safe to be vulnerable with someone?', 'Trust', 'Safety'),
('What would unconditional self-acceptance look like in your life? What would change if you fully embraced who you are?', 'Self-Love', 'Acceptance'),
('Write about the difference between being alone and being lonely. How has your relationship with solitude evolved?', 'Independence', 'Self-Sufficiency'),
('What legacy do you want to leave in terms of how you love and how you allow yourself to be loved?', 'Legacy', 'Purpose');